### ISSUE TITLE
boot support

### ISSUE THREAD

**Issue by lsnape** [mhjort/lein-clj-lambda#10]
I've spent the last few weeks implementing some lambda jobs and have written boot tasks to help with the deploy.

I wanted to open source the tasks, but rather than create a separate repository it would be better if it lived in this project, especially since you've taken the trouble to split out common and leiningen code. The repository might need to be renamed though!

I'm happy to do this, or if you'd prefer to do it yourself then that's fine too :) The offer is there!

**Comment by mhjort** [comment]
Great news! The reason for splitting up the code was to encourage someone to implement Boot support. I can definitely rename the project. I've been thinking it already. Hardest part is naming of course. What about ```clj-lambda-utils``` for example?

**Comment by lsnape** [comment]
`clj-lambda-utils` sounds good to me.

What I'm not certain about yet is what the boot tasks interface should look like. Usually boot tasks take individual parameters, but the config required for setting up a lambda job is quite lengthy – it will need some thought. 

Other changes I'd like to make: support Kinesis event source mapping, and possibly also Cloudwatch Events triggers. Probably makes sense to have those as separate PRs. though.

I've got a lot on my plate for the next week or so, but after that I'll start working on this properly.

**Comment by mhjort** [comment]
You are right. We should redesign the interface. Are you in clojurians slack? We could have a chat there someday?

**Comment by mhjort** [comment]
I renamed the project now to ```clj-lambda-utils```

**Comment by mhjort** [comment]
Made a changes to library. Now API looks like this as specified:

```
(defn update-lambda [environment config jar-file & [opts]])

(defn install-lambda [environment config jar-file & [opts]])
```

I have not released a new version but changes are now in master.
